mozilla-rally/rally

- web-platform/functions/src/__tests__/index.test.ts
- web-platform/functions/src/glean.ts
- web-platform/functions/src/index.ts
- web-platform/functions/src/studies.ts
Migrating functions code from rally-web-platform to rally monorepo.
Fixes: https://github.com/mozilla-rally/rally/issues/29
> Functions migration

- web-platform/website/__mocks__/firebase/auth.js
- web-platform/website/src/components/pages/login/EmailAccountCreatedView.tsx
- web-platform/website/src/components/pages/login/InitialLoginView.tsx
- web-platform/website/src/components/pages/login/LoginDataContext.tsx
- web-platform/website/src/components/pages/login/LoginPageContainer.tsx
- web-platform/website/src/components/pages/login/LoginView.tsx
- web-platform/website/src/components/pages/login/PasswordRuleViolations.tsx
- web-platform/website/src/components/pages/login/PrivacyNoticeAndLoginLink.tsx
- web-platform/website/src/components/pages/login/__tests__/EmailAccountCreatedView.tests.tsx
- web-platform/website/src/components/pages/login/__tests__/LoginPageContainer.tests.tsx
- web-platform/website/src/components/pages/login/__tests__/LoginView.tests.tsx
- web-platform/website/src/components/pages/login/__tests__/PrivacyNoticeAndLoginLink.tests.tsx
- web-platform/website/src/resources/Strings.tsx
- web-platform/website/src/services/AuthenticationService.tsx
- web-platform/website/src/services/UserAccountService.ts
- web-platform/website/src/services/__tests__/AuthenticationService.tests.tsx
- web-platform/website/src/services/__tests__/UserAccountService.tests.ts
- web-platform/website/src/styles/Buttons.ts
- web-platform/website/src/styles/Fonts.ts
- web-platform/website/src/utils/FirebaseErrors.ts
Redirect to homepage when user visits login page already being logged in
Fixes: https://github.com/mozilla-rally/rally/issues/52
> Implement login view

- web-platform/website/__mocks__/firebase/auth.js
- web-platform/website/src/components/AuthenticatedPage.tsx
- web-platform/website/src/components/__tests__/AuthenticatedPage.tests.tsx
- web-platform/website/src/components/pages/login/InitialLoginView.tsx
- web-platform/website/src/components/pages/login/LoginView.tsx
- web-platform/website/src/components/pages/login/__tests__/InitialLoginView.tests.tsx
- web-platform/website/src/components/pages/login/__tests__/LoginView.tests.tsx
- web-platform/website/src/services/AuthenticationService.tsx
- web-platform/website/src/services/UserAccountService.ts
- web-platform/website/src/services/__tests__/AuthenticationService.tests.tsx
- web-platform/website/src/services/__tests__/UserAccountService.tests.ts
- web-platform/website/src/utils/__tests__/FirebaseErrors.tests.ts
Also added unit tests for firebase errors
Fixes:
https://github.com/mozilla-rally/rally/issues/57
https://github.com/mozilla-rally/rally/issues/58
> Implemented login with google

- web-platform/website/__mocks__/firebase/auth.js
- web-platform/website/jest.config.js
- web-platform/website/src/components/pages/login/LoginDataContext.tsx
- web-platform/website/src/components/pages/login/LoginFormValidator.ts
- web-platform/website/src/components/pages/login/LoginPageContainer.tsx
- web-platform/website/src/components/pages/login/LoginView.tsx
- web-platform/website/src/components/pages/login/ResetPasswordView.tsx
- web-platform/website/src/components/pages/login/__tests__/LoginPageContainer.tests.tsx
- web-platform/website/src/components/pages/login/__tests__/LoginView.tests.tsx
- web-platform/website/src/components/pages/login/__tests__/ResetPasswordView.tests.tsx
- web-platform/website/src/resources/Strings.tsx
- web-platform/website/src/services/AuthenticationService.tsx
- web-platform/website/src/services/UserAccountService.ts
- web-platform/website/src/services/__tests__/UserAccountService.tests.ts
Fixed login page container to redirect based on verified user. This ensures we don't get redirected as we are signing up via email / password.
Fixes: https://github.com/mozilla-rally/rally/issues/65
> Reset password implementation

- common/config/rush/npm-shrinkwrap.json
- rush.json
- shared/types/.eslintignore
- shared/types/.eslintrc
- shared/types/.gitignore
- shared/types/.npmignore
- shared/types/package-lock.json
- shared/types/package.json
- shared/types/src/UserDocument.ts
- shared/types/src/UserStudyRecord.ts
- shared/types/tsconfig.json
> Adding shared types

- extensions/attention-stream/metrics.yaml
- extensions/attention-stream/pings.yaml
second attempt at updating the yaml files.
> filled in TODOs for bugs, emails and data review

- web-platform/functions/src/studies.ts
This will need to be deployed to the RWP and activated.
Review expectations:
Just a visual double-check
> pause Facebook Pixel Hunt data collection and mark study ended

- web-platform/website/src/resources/Strings.tsx
> Updated terms and conditions with new customers disclaimer text.

- web-platform/website/src/services/UserDocumentService.tsx
- web-platform/website/src/services/__tests__/UserDocumentService.tests.tsx
Also fixed the unauthenticated case where document loaded was never signaled to true leading to null content.
> Fixes: https://github.com/mozilla-rally/rally/issues/119

- shared/types/src/Study.ts
- web-platform/website/__mocks__/firebase/firestore.js
- web-platform/website/src/components/pages/profile/ProfileButtons.tsx
- web-platform/website/src/components/pages/studies/study-card/AddStudyView.tsx
- web-platform/website/src/components/pages/studies/study-card/StudyCard.tsx
- web-platform/website/src/components/pages/studies/study-card/StudyCardHeader.tsx
- web-platform/website/src/components/pages/studies/study-card/StudyDataContext.tsx
- web-platform/website/src/components/pages/studies/study-card/StudyDescription.tsx
- web-platform/website/src/components/pages/studies/study-card/StudyTitle.tsx
- web-platform/website/src/components/pages/studies/study-card/StudyTopDetails.tsx
- web-platform/website/src/components/pages/studies/study-card/__tests__/AddStudyView.tests.tsx
- web-platform/website/src/components/pages/studies/study-card/__tests__/StudyCard.tests.tsx
- web-platform/website/src/components/pages/studies/study-card/__tests__/StudyCardHeader.tests.tsx
- web-platform/website/src/components/pages/studies/study-card/__tests__/StudyDataContext.tests.tsx
- web-platform/website/src/components/pages/studies/study-card/__tests__/StudyDescription.tests.tsx
- web-platform/website/src/components/pages/studies/study-card/__tests__/StudyTitle.tests.tsx
- web-platform/website/src/components/pages/studies/study-card/__tests__/StudyTopDetails.tests.tsx
- web-platform/website/src/resources/Strings.tsx
- web-platform/website/src/services/UserDocumentService.tsx
- web-platform/website/src/services/__tests__/UserDocumentService.tests.tsx
- web-platform/website/src/styles/DocumentStyles.ts
- web-platform/website/src/styles/Fonts.ts
- web-platform/website/src/utils/BrowserDetector.ts
- web-platform/website/src/utils/BrowserType.ts
- web-platform/website/src/utils/__tests__/BrowserDetector.tests.ts
Added browser specific download link to study schema
> Add study modal dialog

- web-platform/website/src/components/pages/studies/study-card/AddStudyView.tsx
- web-platform/website/src/components/pages/studies/study-card/DontJoinStudyView.tsx
- web-platform/website/src/components/pages/studies/study-card/StudyCard.tsx
- web-platform/website/src/components/pages/studies/study-card/StudyCardHeader.tsx
- web-platform/website/src/components/pages/studies/study-card/__tests__/DontJoinStudyView.tests.tsx
- web-platform/website/src/resources/Strings.tsx
Fixed order of end study enrollment to prevent reactive popup for other dialogs
> Adding dont join study

- web-platform/functions/src/__tests__/index.test.ts
- web-platform/functions/src/index.ts
Closes #110 
Closes #111 
Reviewer expectations:
- Confirm functionality by testing on Stage or in your own environment
- If someone is able to manually test with multiple studies, that would be awesome
- @rhelmer can you test with our current Svelte site?
- @thomik-corp can you test with the new React site?
- Urgency: normal
> Fix delete user

- web-platform/firebase/firebase.config.rally-web-prod.json
- web-platform/firebase/firebase.config.rally-web-stage.json
- web-platform/website/__mocks__/firebase/analytics.js
- web-platform/website/src/__tests__/_app.tests.tsx
- web-platform/website/src/components/pages/account-settings/__tests__/EditAccountEmailView.tests.tsx
- web-platform/website/src/pages/_app.tsx
- web-platform/website/src/services/ExtensionsEventService.ts
- web-platform/website/src/services/FirebaseService.ts
- web-platform/website/src/services/StudiesService.tsx
- web-platform/website/src/services/__tests__/FirebaseService.tests.ts
- web-platform/website/src/services/__tests__/StudiesService.tests.tsx
Fixes: https://github.com/mozilla-rally/rally/issues/136
> Adding google analytics and fixing linting errors.

- web-platform/website/src/components/pages/login/LoginPageContent.tsx
- web-platform/website/src/resources/Strings.tsx
- web-platform/website/src/styles/DocumentStyles.ts
Fixes:
- https://github.com/mozilla-rally/rally/issues/164
- https://github.com/mozilla-rally/rally/issues/178
- https://github.com/mozilla-rally/rally/issues/171
> Fixes several bugs

- .github/workflows/build-and-publish.yaml
- .github/workflows/build.yaml
- extensions/attention-stream/manifest.dev.json
- extensions/attention-stream/manifest.prod.json
- extensions/attention-stream/package-lock.json
- extensions/attention-stream/package.json
- extensions/attention-stream/src/background.ts
This produces automated builds for Firefox, I'll add Chrome support in a followup.
> Publish attention-stream extension from CI

- web-platform/website/public/img/error.svg
- web-platform/website/src/components/AuthenticatedPage.tsx
- web-platform/website/src/components/__tests__/AuthenticatedPage.tests.tsx
- web-platform/website/src/components/pages/account-settings/__tests__/EditAccountEmailView.tests.tsx
- web-platform/website/src/components/pages/login/EmailSignupView.tsx
- web-platform/website/src/components/pages/login/LoginDataContext.tsx
- web-platform/website/src/components/pages/login/LoginView.tsx
- web-platform/website/src/components/pages/login/UnverifiedEmailError.tsx
- web-platform/website/src/components/pages/login/__tests__/EmailSignupView.tests.tsx
- web-platform/website/src/components/pages/login/__tests__/LoginDataContext.tests.tsx
- web-platform/website/src/components/pages/login/__tests__/LoginView.tests.tsx
- web-platform/website/src/components/pages/login/__tests__/UnverifiedEmailError.tests.tsx
- web-platform/website/src/resources/Strings.tsx
- web-platform/website/src/services/AuthenticationService.tsx
- web-platform/website/src/services/UserAccountService.ts
- web-platform/website/src/services/UserDocumentService.tsx
- web-platform/website/src/services/__tests__/AuthenticationService.tests.tsx
- web-platform/website/src/services/__tests__/UserAccountService.tests.ts
- web-platform/website/src/services/__tests__/UserDocumentService.tests.tsx
> Fix: https://github.com/mozilla-rally/rally/issues/172

- web-platform/website/src/components/navigation-bar/NavigationBar.tsx
- web-platform/website/src/components/pages/account-settings/AccountSettingsMobileNavigationBar.tsx
- web-platform/website/src/components/pages/account-settings/AccountSettingsNavigationBar.tsx
- web-platform/website/src/components/pages/account-settings/AccountSettingsNavigationBarWrapper.tsx
- web-platform/website/src/components/pages/account-settings/AccountSettingsPageContent.tsx
- web-platform/website/src/components/pages/account-settings/DeleteAccountView.tsx
- web-platform/website/src/components/pages/account-settings/EditAccountEmailView.tsx
- web-platform/website/src/components/pages/account-settings/EditAccountPasswordView.tsx
- web-platform/website/src/components/pages/login/EmailSignupView.tsx
- web-platform/website/src/components/pages/login/LoginView.tsx
- web-platform/website/src/components/pages/profile/ProfilePageContent.tsx
- web-platform/website/src/components/pages/studies/StudiesPageContent.tsx
- web-platform/website/src/components/pages/studies/StudiesTooltip.tsx
- web-platform/website/src/resources/Strings.tsx
- web-platform/website/src/styles/Buttons.ts
- web-platform/website/src/styles/Columns.ts
- web-platform/website/src/styles/ContainerStyles.ts
- web-platform/website/src/styles/Fonts.ts
**This PR adds the mobile navigation bar to the account page.**
**Aligns all the view (Studies, Profile, and account):**
**And adds the nav and footer to the profile page:**
**Adds error feedback to field (red with warning icon) when user breaks the password rules during email signup:**
**And finally, adds eyes icons to signup password forms to users can show and hide password as they type:**
closes #140
closes #165 
closes #166 
closes #182 
closes #183
> mobile account nav 

- web-platform/website/src/__tests__/PrivacyPolicyPage.tests.tsx
- web-platform/website/src/components/AuthenticatedPage.tsx
- web-platform/website/src/components/__tests__/AuthenticatedPage.tests.tsx
- web-platform/website/src/components/pages/profile/ProfileButtons.tsx
- web-platform/website/src/components/pages/profile/__tests__/ProfileButtons.tests.tsx
- web-platform/website/src/pages/privacy-policy.tsx
> Fixes: https://github.com/mozilla-rally/rally/issues/177

- web-platform/website/src/components/pages/studies/StudyList.tsx
- web-platform/website/src/components/pages/studies/__tests__/StudyList.tests.tsx
Fixes: https://github.com/mozilla-rally/rally/issues/213
> Filter out expired, paused and browser incompatible studies.

- web-platform/website/src/components/pages/privacy-policy/PrivacyPolicyButtons.tsx
- web-platform/website/src/components/pages/studies/study-card/AddStudyView.tsx
- web-platform/website/src/components/pages/studies/study-card/StudyTopDetails.tsx
- web-platform/website/src/services/UserDocumentService.tsx
- web-platform/website/src/services/__tests__/UserDocumentService.tests.tsx
Study was being duplicated as a field in addition to collection.
> Fixing linting and dedup study information in users row.

- web-platform/functions/src/studies.ts
> bump attention-stream version, and use consistent store ID in store URLs

- web-platform/website/src/components/pages/studies/study-card/AddStudyView.tsx
- web-platform/website/src/components/pages/studies/study-card/DontJoinStudyView.tsx
- web-platform/website/src/components/pages/studies/study-card/LeaveStudyView.tsx
- web-platform/website/src/components/pages/studies/study-card/__tests__/AddStudyView.tests.tsx
- web-platform/website/src/components/pages/studies/study-card/__tests__/DontJoinStudyView.tests.tsx
- web-platform/website/src/components/pages/studies/study-card/__tests__/LeaveStudyView.tests.tsx
- web-platform/website/src/services/AuthenticationService.tsx
- web-platform/website/src/services/__tests__/AuthenticationService.tests.tsx
Fixes: https://github.com/mozilla-rally/rally/issues/234
> Added logEvent to study leave, join and signed in states.

- web-platform/website/src/components/pages/login/LoginPageContent.tsx
- web-platform/website/src/services/ExtensionsEventService.ts
- web-platform/website/src/services/__tests__/ExtensionsEventService.tests.ts
Hide login bullets when navigating away from initial login screen
> Hide login bullets when navigating away from initial login screen

- web-platform/website/src/components/pages/login/LoginView.tsx
Fix: https://github.com/mozilla-rally/rally/issues/242
Normal state:
Invalid password:
> Entering incorrect password on email login doesn't show error text #242

- QA_CHECKLIST.md
Closes #265
First draft of manual testing checklist
I am imagining we could link off to other documents for certain steps where needed with more specific info about how to verify
> initial Rally QA checklist

- web-platform/website/src/resources/Strings.tsx
> Study-specific block updated on privacy policy

- web-platform/functions/src/__tests__/index.test.ts
- web-platform/functions/src/index.ts
Use new page from https://github.com/mozilla-rally/site/pull/719
> change offboarding URL

- .github/workflows/build-and-publish.yaml
- .github/workflows/build.yaml
- web-platform/firebase/firestore.rules
Email verification should not block onboarding.
> remove email verification requirement

- web-platform/website/src/services/StudiesService.tsx
- web-platform/website/src/services/__tests__/StudiesService.tests.tsx
Addresses https://github.com/mozilla-rally/rally/issues/322
> Do not fire activate_extension from study service

- web-platform/website/src/components/pages/login/LoginPageContentV2.tsx
- web-platform/website/src/components/pages/login/__tests__/LoginPageContentV2.tests.tsx
- web-platform/website/src/resources/Strings.tsx
Account first:
Extension first:
> Added conditional string for account first case

- web-platform/website/src/__tests__/LoginPage.tests.tsx
- web-platform/website/src/components/pages/login/EmailSignupView.tsx
- web-platform/website/src/components/pages/login/InitialLoginView.tsx
- web-platform/website/src/components/pages/login/__tests__/EmailSignupView.tests.tsx
- web-platform/website/src/components/pages/login/__tests__/InitialLoginView.tests.tsx
- web-platform/website/src/pages/login.tsx
- web-platform/website/src/resources/Flags.ts
- web-platform/website/src/services/Flag.ts
- web-platform/website/src/services/FlagService.tsx
- web-platform/website/src/services/__tests__/FlagService.tests.tsx
- Allows us to turn on and off experiments by changing a boolean via code commit
- Tested locally with turning flag on/off by changing default value
> Default value for experiments

- web-platform/website/src/components/pages/login/EmailSignupView.tsx
- web-platform/website/src/components/pages/login/__tests__/EmailSignupView.tests.tsx
- web-platform/website/src/resources/Strings.tsx
- web-platform/website/src/styles/Buttons.ts
- web-platform/website/src/styles/Colors.ts
> Added green highlight button for in-progress sign in

- extensions/attention-stream/manifest-template.json
Fixes https://github.com/mozilla-rally/rally/issues/356
> change extension homepage to members site

- shared/types/src/UserDocument.ts
- web-platform/website/src/__tests__/LoginPage.tests.tsx
- web-platform/website/src/components/pages/login/EmailSignupView.tsx
- web-platform/website/src/components/pages/login/__tests__/EmailSignupView.tests.tsx
- web-platform/website/src/pages/login.tsx
- web-platform/website/src/resources/Strings.tsx
> Consent checkbox

- web-platform/functions/src/index.ts
> Disable Glean ping trigger for study unenrollment

- web-platform/website/src/resources/Flags.ts
This PR shall only be submitted post testing.
Cleanup shall be done in another followup PR.
> Setting default value of onboardingV2 flag to true.

- shared/types/src/UserDocument.ts
- web-platform/website/src/__tests__/_app.tests.tsx
- web-platform/website/src/components/AuthenticatedPage.tsx
- web-platform/website/src/components/__tests__/AuthenticatedPage.tests.tsx
- web-platform/website/src/pages/_app.tsx
- web-platform/website/src/services/AttributionService.tsx
- web-platform/website/src/services/UserDocumentService.tsx
- web-platform/website/src/services/__tests__/AttributionService.tests.tsx
Fixes https://github.com/mozilla-rally/rally/issues/373
> store utm codes in firestore, do not allow overwriting

- extensions/attention-stream/src/background.ts
Fixes issue https://github.com/mozilla-rally/rally/issues/425
> add ability to open new tab page on update only

- web-platform/functions/src/index.ts
Review expectations: This just changes this from an HTTP-triggered function to run on a schedule, I will test this on stage before deploying. OK to just look, it should be possible to write automated tests against the emulator but this is still in flux so I haven't tried yet.
> count Rally users and extensions from auth db hourly and log

- web-platform/website/src/components/pages/studies/study-card/StudyDescription.tsx
> Correct study details link in study card

- web-platform/website/src/components/pages/get-extension/GetExtensionView.tsx
- web-platform/website/src/components/pages/studies/SurveyCard.tsx
This PR addressed some button bugs on the add extension page and survey card on the home page.
closes #470 
closes #468
> button bugs fix

- web-platform/website/src/components/Footer.tsx
- web-platform/website/src/components/navigation-bar/NavigationBar.tsx
Fixed https://github.com/mozilla-rally/rally/issues/504
Verified in GA
> Fixed https://github.com/mozilla-rally/rally/issues/504

- web-platform/website/src/resources/Strings.tsx
> Updated graph for pixel tracker

- web-platform/website/src/components/pages/home/news/NewsItem.tsx
- web-platform/website/src/resources/Strings.tsx
> Updated news text from official copy.

- web-platform/website/src/resources/Flags.ts
- web-platform/website/src/resources/Strings.tsx
> Launch homepage v2

- web-platform/website/src/pages/login.tsx
> Move useFlagService hook so that it's not called conditionally
